### ISSUE TITLE
#<RuntimeError: Build failed>

### ISSUE THREAD

**Issue by erisco** [bitrise-io/steps-xamarin-test-cloud-for-ios#21]
I know the build error is because we do not have an appropriate certificate. My guess is that the response to this problem isn't supposed to be a stack trace, however.

```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets : error: No valid iOS code signing keys found in keychain. You need to request a codesigning certificate from https://developer.apple.com.
#<RuntimeError: Build failed>
--- Stack trace: ---
["/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise303651240/step_src/xamarin-builder/builder.rb:34:in `block in build'", "/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise303651240/step_src/xamarin-builder/builder.rb:29:in `each'", "/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise303651240/step_src/xamarin-builder/builder.rb:29:in `build'", "/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise303651240/step_src/step.rb:184:in `<main>'"]
```

**Comment by godrei** [comment]
Hi @erisco ,
thanks for reporting!
What is your suggestion? How it should look?

**Comment by erisco** [comment]
@godrei it looks as erroneous as `#<TypeError: no implicit conversion of nil into String>`. Is this the output for an uncaught exception? I would catch the exception and print an error message which makes it obvious that the program was expecting this failure.

For example, you could just print:

```
Build failed.
```

**Comment by godrei** [comment]
This is an caught exception.
The stack trace helps to support our users and identify the issues.

Simply printing `Build failed.` would hide the source of the error.
